export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** An ISO 8601-encoded datetime */
  ISO8601DateTime: { input: string; output: string; }
};

export type Account = {
  __typename?: 'Account';
  accountType: Scalars['String']['output'];
  balance: Scalars['Int']['output'];
  createdAt: Scalars['ISO8601DateTime']['output'];
  id: Scalars['ID']['output'];
  name: Scalars['String']['output'];
  updatedAt: Scalars['ISO8601DateTime']['output'];
  userId: Scalars['Int']['output'];
};

export type Category = {
  __typename?: 'Category';
  id: Scalars['ID']['output'];
  name: Scalars['String']['output'];
  /** List of transactions associated with this category */
  transactions?: Maybe<Array<Transaction>>;
};

/** Autogenerated input type of CreateAccount */
export type CreateAccountInput = {
  accountType: Scalars['String']['input'];
  balance: Scalars['Float']['input'];
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  name: Scalars['String']['input'];
};

/** Autogenerated return type of CreateAccount. */
export type CreateAccountPayload = {
  __typename?: 'CreateAccountPayload';
  account: Account;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
};

/** Autogenerated input type of DeleteAccount */
export type DeleteAccountInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['Int']['input'];
};

/** Autogenerated return type of DeleteAccount. */
export type DeleteAccountPayload = {
  __typename?: 'DeleteAccountPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  success: Scalars['Boolean']['output'];
};

export type Expense = {
  __typename?: 'Expense';
  account: Account;
  category: Category;
  expenseDate: Scalars['ISO8601DateTime']['output'];
  id: Scalars['ID']['output'];
  isRecurring: Scalars['Boolean']['output'];
  recurringPeriod: Scalars['Int']['output'];
  transactions: Array<Transaction>;
  user: User;
};

export type FinancialSummary = {
  __typename?: 'FinancialSummary';
  /** Total balance of accounts */
  totalBalance: Scalars['Float']['output'];
  /** Total of expenses */
  totalExpenses: Scalars['Float']['output'];
  /** Total of incomes */
  totalIncomes: Scalars['Float']['output'];
  /** Total of savings */
  totalSavings: Scalars['Float']['output'];
  /** Total savings of current month */
  totalSavingsByCurrentMonth: Scalars['Float']['output'];
  userId: Scalars['Int']['output'];
};

export type Income = {
  __typename?: 'Income';
  account: Account;
  category: Category;
  id: Scalars['ID']['output'];
  incomeDate: Scalars['ISO8601DateTime']['output'];
  isRecurring: Scalars['Boolean']['output'];
  recurringPeriod: Scalars['Int']['output'];
  transactions: Array<Transaction>;
  user: User;
};

export type Mutation = {
  __typename?: 'Mutation';
  /** Create a new account */
  createAccount?: Maybe<CreateAccountPayload>;
  /** Delete related account */
  deleteAccount?: Maybe<DeleteAccountPayload>;
  /** Update the related account */
  updateAccount?: Maybe<Account>;
};


export type MutationCreateAccountArgs = {
  input: CreateAccountInput;
};


export type MutationDeleteAccountArgs = {
  input: DeleteAccountInput;
};


export type MutationUpdateAccountArgs = {
  input: UpdateAccountInput;
};

export type Query = {
  __typename?: 'Query';
  /** All financial accounts */
  accounts: Array<Account>;
  /** All expenses */
  expenses: Array<Expense>;
  /** Summary of user's financial data like total income */
  financialSummary?: Maybe<FinancialSummary>;
  /** All incomes */
  incomes: Array<Income>;
  /** Recent transactions data */
  recentTransactions?: Maybe<Array<Transaction>>;
  /** All user details */
  user: User;
};

/** Properties of Transaction */
export type Transactable = Expense | Income;

export type Transaction = {
  __typename?: 'Transaction';
  amount: Scalars['Float']['output'];
  description?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  transactable: Transactable;
  transactionDate: Scalars['ISO8601DateTime']['output'];
  user: User;
};

/** Autogenerated input type of UpdateAccount */
export type UpdateAccountInput = {
  accountType?: InputMaybe<Scalars['String']['input']>;
  balance?: InputMaybe<Scalars['Float']['input']>;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['Int']['input'];
  name?: InputMaybe<Scalars['String']['input']>;
};

export type User = {
  __typename?: 'User';
  createdAt: Scalars['ISO8601DateTime']['output'];
  email: Scalars['String']['output'];
  firstName: Scalars['String']['output'];
  fullName: Scalars['String']['output'];
  fullNameWithMiddle: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  lastName: Scalars['String']['output'];
  updatedAt: Scalars['ISO8601DateTime']['output'];
};
