databases:
  - name: expen_zen
    databaseName: expen_zen
    user: expen_zen

services:
  - type: web
    name: expen_zen
    runtime: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: expen_zen
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
